services:
  # Backend Service
  - type: web
    name: neora-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: |
      cd backend
      daphne neora.asgi:application --bind 0.0.0.0 --port $PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://neora-frontend-hh8f.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://neora-frontend-hh8f.onrender.com"
      - key: FRONTEND_BASE_URL
        value: "https://neora-frontend-hh8f.onrender.com"
      - key: BACKEND_BASE_URL
        value: "https://neora-backend-zl4q.onrender.com"
      - key: REDIS_URL
        fromService:
          type: redis
          name: neora-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: neora-db
          property: connectionString

  # Frontend Service
  - type: web
    name: neora-frontend
    env: static
    buildCommand: |
      cd frontend/neora-frontend
      npm install -g pnpm
      pnpm install --no-frozen-lockfile
      pnpm run build
    staticPublishPath: ./frontend/neora-frontend/dist
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: VITE_API_BASE_URL
        value: "https://neora-backend-zl4q.onrender.com/api"
      - key: VITE_WS_BASE_URL
        value: "wss://neora-backend-zl4q.onrender.com/ws"

  # Redis Service
  - type: redis
    name: neora-redis
    plan: free
    ipAllowList: []

databases:
  # PostgreSQL Database
  - name: neora-db
    plan: free
