services:
  # Backend Service
  - type: web
    name: neora-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: |
      cd backend
      daphne neora.asgi:application --bind 0.0.0.0 --port $PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://neora-frontend-hh8f.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://neora-frontend-hh8f.onrender.com"
      - key: FRONTEND_BASE_URL
        value: "https://neora-frontend-hh8f.onrender.com"
      - key: BACKEND_BASE_URL
        value: "https://neora-backend-zl4q.onrender.com"
      - key: REDIS_URL
        fromService:
          type: redis
          name: neora-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: neora-db
          property: connectionString
      # Email Configuration
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_HOST_USER
        value: "your-email@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "your-app-password"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "true"
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@neora.com"
      # n8n AI Integration
      - key: N8N_WEBHOOK_URL
        value: "https://your-n8n-instance.com/webhook/neora-chat"
      - key: N8N_BASIC_AUTH
        value: "your-username:your-password"
      - key: N8N_API_KEY_HEADER
        value: "X-API-Key"
      - key: N8N_API_KEY_VALUE
        value: "your-api-key"
      # Optional Features
      - key: ENABLE_TRANSCRIPTION
        value: "false"
      - key: LANGUAGE_CODE
        value: "en"
      - key: TIMEZONE
        value: "Asia/Riyadh"

  # Frontend Service
  - type: web
    name: neora-frontend
    env: static
    buildCommand: |
      cd frontend/neora-frontend
      npm install -g pnpm
      pnpm install --no-frozen-lockfile
      pnpm run build
    staticPublishPath: ./frontend/neora-frontend/dist
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: VITE_API_BASE_URL
        value: "https://neora-backend-zl4q.onrender.com/api"
      - key: VITE_WS_BASE_URL
        value: "wss://neora-backend-zl4q.onrender.com/ws"

  # Redis Service
  - type: redis
    name: neora-redis
    plan: free
    ipAllowList: []

databases:
  # PostgreSQL Database
  - name: neora-db
    plan: free
